# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ad7343f27570a3d011caf9de945ec06571145a5ae9b76babbdd15b76368979acb2bac8ae99cd697278b3b424c754131d69d98fc7e6f6b014f0b5f13fe914891

test:
  secret_key_base: 1e4867d4b09742db7fe955c2c853106a4cf7710b3f1967117533f29f0af04ad5b3a5a700d36950f5204d0afb62cc0e4c099e56c08d6d6ca5371ddbb6dd454034

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
